import { version } from '../../package.json'

export const environment = {
  production: false,
  appVersion: version,
  BACKEND_ITA_CHALLENGE_BASE_URL: '/itachallenge/api/v1',
  BACKEND_ITA_CHALLENGE_SOLUTION: '/challenge/solution',
  BACKEND_ITA_CHALLENGE_USER_SOLUTION: '/user/solution',
  BACKEND_USER_FAVORITES: '/user/users',
  BACKEND_ITA_CHALLENGE_TAGS: '/tags',
  BACKEND_ITA_SSO_BASE_URL: 'https://dev.sso.itawiki.eurecatacademy.org/api/v1',
  BACKEND_ITA_WIKI_BASE_URL: 'https://dev.itawiki.eurecatacademy.org/api/v1',
  BACKEND_ITA_WIKI_RESOURCES: '/resources',
  BACKEND_ITA_WIKI_CATEGORIES: '/categories',
  BACKEND_ALL_CHALLENGES_URL: '/challenge/challenges',
  BACKEND_ITA_FAVORITES: '/favorite/challenges',
  BACKEND_ALL_LANGUAGE_URL: '/languages/',
  BACKEND_SSO_ITINERARIES: '/itineraries',
  BACKEND_SSO_LOGIN_URL: '/auth/login',
  BACKEND_SSO_POST_USER: '/users/me',
  BACKEND_SSO_PATCH_USER: '/users',
  BACKEND_SSO_REGISTER_URL: '/auth/register',
  BACKEND_SSO_VALIDATE_TOKEN_URL: '/tokens/validate',
  BACKEND_GITHUB_VALIDATE_ENDPOINT: '/auth/github/authenticate',
  BACKEND_LOGOUT_ENDPOINT: '/auth/logout',
  ADMIN_USER: '../assets/dummy/admin-user.json',
  USER_SOLUTION: '/user/users/',
  ITINERARY_ID: 'clpb8t1cc000008k0cg1icvl4',
  AUTHORIZATION: 'Authorization',
  BEARER: 'Bearer ',
  BACKEND_TOKEN: '',
  pageSize: 8,
  SECRET_PASSWORD: '985a459f34645aec05f978bfda43aebd2212f70542d3100e16c862c0f329d323',
  HTTP_CODE_SUCCESS: 200,
  HTTP_CODE_BAD_REQUEST: 400,
  HTTP_CODE_UNAUTHORIZED: 401,
  HTTP_CODE_FORBIDDEN: 403,
  GITHUB_CLIENT_ID: 'Ov23liMlfGdUlcA569gk',
  AUTH_REDIRECT_URL: 'http://localhost:4200/ita-challenge/challenges',
  AUTH_BASIC_URL: 'http://localhost:4200/ita-challenge/',
  AUTH_SWITCH_ROLE: '/auth/switch-role',
  GITHUB_PROFILE_URL: 'https://api.github.com/users/',
  ADMIN: {
    CREATE_USER: '/admin/users/create',
  },
}
