name: Upload Image to Docker Hub

on:
  push:
    branches:
      - workflow

jobs:
  #sonarcloud:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4
        #with:
          #fetch-depth: 0

      #- name: Setup Node.js
        #uses: actions/setup-node@v4
        #with:
          #node-version: '20'

      #- name: SonarCloud Scan
        #uses: sonarsource/sonarcloud-github-action@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    #needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Load env from file
        run: |
          echo "Loading env vars from .env file"
          while IFS='=' read -r key value
          do
            key=$(echo $key | tr '.' '_')
            echo "$key=$value" >> $GITHUB_ENV
          done < conf/.env.CI.dev
          echo "Done"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run:  |
          npx ng build --configuration production
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: itacademybcn/itachallenges:itachallenge-nginx-${{ env.MICROSERVICE_VERSION }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ./deploy_frontend_dev.sh
          env:
            VAR1: itachallenge-nginx
            VAR2: ${{ env.MICROSERVICE_VERSION }}